### PR TITLE
add ability to open org files with text editor

### PR DESCRIPTION
**Pull request by andres-nav**
What does this implement/fix? Explain your changes.
---------------------------------------------------

It just allows users to edit also `.org` files that are simple text files.

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**iOS Version:** …

**MEGA Version:** …

### CODE REVIEW

**Comment by andres-nav** [comment]
@MrRR0112  I have opened the pull request again as it was not merge due to my mistake of removing the fork.

If you could please merge it, I would really appreciate it as it is a big knit pick of mine :)

**Comment by tomekkuzma-mega** [comment]
Hey, @mega-mvc can you pull that work in?

**Comment by mega-ios-hiring** [comment]
Hello @andres-nav 

We are going to handle it internally and we will address this problem after the version 14.2

Thank you for raising this pull request.

**Comment by jnavarrom** [comment]
Hello @andres-nav

We are going to handle it internally and we will address this problem after the version 14.2

Thank you for raising this pull request.

**Pull request closed without merging**
